### ISSUE TITLE
Input shape mismatch  error during training

### ISSUE THREAD

**Issue by cogmeta** [castorini/honkling#91]
I am getting following error:
python training.py -d ../data/go/ -cgo
tensorflow                    1.12.0  
keras 2.2.4

training model with learning rate = 0.1, num epochs = 26, batch size = 64
training start time = 2019-02-22 15:54:26
Traceback (most recent call last):
  File "training.py", line 445, in <module>
    main()
  File "training.py", line 410, in main
    verbose=0)
  File "/home/psasatte/.local/lib/python2.7/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/home/psasatte/.local/lib/python2.7/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/home/psasatte/.local/lib/python2.7/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input to have 4 dimensions, but got array with shape (0, 1)

**Comment by cogmeta** [comment]
Ok, i was able to run on speech commands.
