### ISSUE TITLE
Weight file format

### ISSUE THREAD

**Issue by cogmeta** [castorini/honkling#92]
Format of  node_js/src/weights/RES8_NARROW.js and the weight file created by training.py do not have same format. How to convert the file created by training.py into format similar to node_js/src/weights/RES8_NARROW.js ? Thanks.

**Comment by cogmeta** [comment]
I tried loading the raw weight file generated by training.py but it does not work.
![image](https://user-images.githubusercontent.com/10062479/53258508-ca910d00-36f2-11e9-8b5f-fd8496cf19e3.png)

**Comment by ljj7975** [comment]
Sorry. iirc training.py is outdated.
Use [`honkling` branch of honk](https://github.com/castorini/honk/tree/honkling), to train a model and genrate js weight files
What you want is in these lines : https://github.com/castorini/honk/blob/honkling/utils/train.py#L154-L161

**Comment by cogmeta** [comment]
@ljj7975 Thanks. will give it a try. Btw, awesome job on honkling. Thank you so much!

**Comment by ljj7975** [comment]
@cogmeta let me know if you get it working so that I can close this issue once you are done.

**Comment by cogmeta** [comment]
python3  -m utils.train  --no_cuda --wanted_words yes no  --dev_every 1 --n_labels 2 --n_epochs 26 --weight_decay 0.00001 --lr 0.1 0.01 0.001 --schedule 3000 6000 --model res8-narrow
yes , folder size -  2377 , missing count -  0
no , folder size -  2375 , missing count -  0
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/psasatte/exp/honk/utils/train.py", line 211, in <module>
    main()
  File "/home/psasatte/exp/honk/utils/train.py", line 201, in main
    train(config)
  File "/home/psasatte/exp/honk/utils/train.py", line 113, in train
    for _, (model_in, labels) in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/psasatte/exp/honk/utils/model.py", line 399, in __getitem__
    return self.preprocess(self.audio_files[index]), self.audio_labels[index]
  File "/home/psasatte/exp/honk/utils/model.py", line 295, in preprocess
    data = torch.from_numpy(preprocess_audio(data, self.n_mels, self.filters))
  File "/home/psasatte/exp/honk/utils/manage_audio.py", line 18, in preprocess_audio
    data = librosa.feature.melspectrogram(data, sr=16000, n_mels=n_mels, hop_length=160, n_fft=480, fmin=20, fmax=4000)
  File "/usr/local/lib/python3.5/dist-packages/librosa/feature/spectral.py", line 1391, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,241) (0,)

**Comment by ljj7975** [comment]
I found that librosa version was outdated. you need v0.6.2.
`pip install librosa --upgrade librosa==0.6.2`

**Comment by cogmeta** [comment]
Awesome! It is building models. will check if i can load models in browser soon. Thank you so much.

**Comment by cogmeta** [comment]
The model was built successfully however i will trouble loading it now..
![image](https://user-images.githubusercontent.com/10062479/53686170-c3e54400-3d49-11e9-80f2-dcb963d46b8c.png)

**Comment by cogmeta** [comment]
Works, Thank you so much. Closing it.
